# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

@typing.final
class LagrangeInterpolator:
    r"""
    Lagrange Polynomial Interpolator
    
    A stateful interpolator that fits a Lagrange polynomial through data points
    and allows evaluation at arbitrary points.
    
    # Attributes
    
    * `x_values` - Stored x coordinates of fitted data points
    * `y_values` - Stored y coordinates of fitted data points
    * `fitted` - Whether the interpolator has been fitted with data
    """
    def __new__(cls) -> LagrangeInterpolator:
        r"""
        Create a new Lagrange interpolator
        
        Returns
        -------
        LagrangeInterpolator
            A new, unfitted interpolator instance
        """
    def fit(self, x: typing.Sequence[builtins.float], y: typing.Sequence[builtins.float]) -> None:
        r"""
        Fit the interpolator with data points
        
        Stores the data points for later evaluation. The Lagrange polynomial
        is constructed implicitly and evaluated on-demand.
        
        Parameters
        ----------
        x : list of float
            X coordinates of data points
        y : list of float
            Y coordinates of data points
        
        Raises
        ------
        ValueError
            If x and y have different lengths or if either is empty
        
        Examples
        --------
        >>> interp = LagrangeInterpolator()
        >>> interp.fit([0.0, 1.0, 2.0], [0.0, 1.0, 4.0])
        """
    def __call__(self, x: typing.Any) -> typing.Any:
        r"""
        Evaluate the interpolation at one or more points
        
        Parameters
        ----------
        x : float or list of float
            Point(s) at which to evaluate the interpolation
        
        Returns
        -------
        float or list of float
            Interpolated value(s) at the specified point(s)
        
        Raises
        ------
        ValueError
            If the interpolator has not been fitted
            If input is neither a float nor a list of floats
        
        Examples
        --------
        >>> interp = LagrangeInterpolator()
        >>> interp.fit([0.0, 1.0, 2.0], [0.0, 1.0, 4.0])
        >>> interp(1.5)  # Single point
        2.25
        >>> interp([0.5, 1.5])  # Multiple points
        [0.25, 2.25]
        """
    def __repr__(self) -> builtins.str:
        r"""
        String representation of the interpolator
        
        Returns
        -------
        str
            Description of the interpolator state
        """

